baseURL: "/"
languageCode: "en-us"
title: "Azimuth"

menu:
    main:
        - name: "Home"
          url: "/"
          weight: 1
        - name: "References"
          url: "/references"
          weight: 2
        - name: "Test"
          url: "/test"
          weight: 3


markup:
    goldmark:
        renderer:
            unsafe: true

params:
    description: "Azimuth: An app for reference-based single-cell analysis"


